
@VIDEO_ID=e16cb196-fd7a-4ec1-b1ca-67321915d4dc
@RESPONSE_FORMAT=- Subject: [Detailed character/object description with 15+ specific physical attributes, clothing, age, build, facial features, ethnicity, hair, eyes, posture, mannerisms, emotional state] -Action: [Specific actions, movements, gestures, behaviors, timing, sequence, transitions, micro-expressions, body language, interaction patterns]- Scene: [Detailed environment description including location, props, background elements, lighting setup, weather, time of day, architectural details]- Style: [Camera shot type, angle, movement, lighting style, visual aesthetic, aspect ratio, film grade, color palette, depth of field, focus techniques]



### Get all videos in library  ====================================
POST https://vision-agent.api.reka.ai/videos/list
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}

### Caption a video by ID  ====================================
POST https://vision-agent.api.reka.ai/qa/chat
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_id": "{{VIDEO_ID}}",
    "messages": [
        {
        "role": "user",
        "content": "What is happening in this video? Reply using this format: {{RESPONSE_FORMAT}}"
        }
    ]
}


### Upload a video ====================================
POST https://vision-agent.api.reka.ai/videos/upload
X-Api-Key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-b.mp4"
Content-Type: video/mp4

< ../assets/test-b.mp4

--WebAppBoundary
Content-Disposition: form-data; name="video_name"

test-b.mp4
--WebAppBoundary
Content-Disposition: form-data; name="index"

true
--WebAppBoundary--




### Upload a photo ====================================
POST https://vision-agent.api.reka.ai/images/upload
X-Api-Key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="test-a.png"
Content-Type: image/png

< ../assets/test-a.png

--WebAppBoundary
Content-Disposition: form-data; name="metadata"

string
--WebAppBoundary--








### Delete a video by ID ====================================
POST https://vision-agent.api.reka.ai/videos/delete
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}