
@VIDEO_ID=e16cb196-fd7a-4ec1-b1ca-67321915d4dc


### Get all videos in library  ====================================
POST https://vision-agent.api.reka.ai/videos/list
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}


### List in images  ====================================
POST https://vision-agent.api.reka.ai/images/list
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}




### Caption a video by ID  ====================================
POST https://vision-agent.api.reka.ai/qa/chat
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_id": "{{VIDEO_ID}}",
    "messages": [
        {
        "role": "user",
        "content": "Write a prompt, in plain text (no marldown), that would generate this exact video using an AI image generation model"
        }
    ]
}




### Upload a video ====================================
POST https://vision-agent.api.reka.ai/videos/upload
X-Api-Key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-b.mp4"
Content-Type: video/mp4

< ../assets/test-b.mp4

--WebAppBoundary
Content-Disposition: form-data; name="video_name"

test-b.mp4
--WebAppBoundary
Content-Disposition: form-data; name="index"

true
--WebAppBoundary--




### Upload a photo ====================================
POST https://vision-agent.api.reka.ai/images/upload
X-Api-Key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="test-a.png"
Content-Type: image/png

< ../assets/test-a.png

--WebAppBoundary
Content-Disposition: form-data; name="metadata"

string
--WebAppBoundary--








### Delete a video by ID ====================================
POST https://vision-agent.api.reka.ai/videos/delete
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}