
@VIDEO_ID=e16cb196-fd7a-4ec1-b1ca-67321915d4dc

@IMAGE_URL=https://guardian-user-uploads-prod.cdn.reka.ai/88563e20-2f3c-4e6d-b802-03121524c1a1/images/5f8604b1a7962408d6240957f38ca935/test-a.png


### Get all videos in library  ====================================
POST https://vision-agent.api.reka.ai/videos/list
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}


### List in images  ====================================
POST https://vision-agent.api.reka.ai/images/list
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}




### Caption a video by ID  ====================================
POST https://vision-agent.api.reka.ai/qa/chat
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_id": "{{VIDEO_ID}}",
    "messages": [
        {
        "role": "user",
        "content": "Write a prompt, in plain text (no marldown), that would generate this exact video using an AI image generation model"
        }
    ]
}


### Caption a video by ID  ====================================
POST https://vision-agent.api.reka.ai/images/chat
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "image_id": "{{VIDEO_ID}}",
    "messages": [
        {
        "role": "user",
        "content": "Write a prompt, in plain text (no marldown), that would generate this exact image using an AI image generation model"
        }
    ]
}



### Caption a image by URL  ====================================
POST https://api.reka.ai/v1/chat/completions
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "messages": [
        {
            "role":"user",
            "content": [
                {
                    "type": "image_url", 
                    "image_url": "{{IMAGE_URL}}"
                },
                {
                    "type": "text", 
                    "text": "Write a prompt, in plain text (no marldown), that would generate this exact image using an AI image generation model. Be detailed in your description, the sublect, the colors, the lighting, the mood, and the style., the style of the image."
                }
            ]
        }
    ],
    "model": "reka-flash"
}


### Upload a video ====================================
POST https://vision-agent.api.reka.ai/videos/upload
X-Api-Key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-b.mp4"
Content-Type: video/mp4

< ../assets/test-b.mp4

--WebAppBoundary
Content-Disposition: form-data; name="video_name"

test-b.mp4
--WebAppBoundary
Content-Disposition: form-data; name="index"

true
--WebAppBoundary--




### Upload a photo ====================================
POST https://vision-agent.api.reka.ai/images/upload
X-Api-Key: {{API_KEY}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="images"; filename="test-a.png"
Content-Type: image/png

< ../assets/test-a.png

--WebAppBoundary
Content-Disposition: form-data; name="metadata"

string
--WebAppBoundary--








### Delete a video by ID ====================================
POST https://vision-agent.api.reka.ai/videos/delete
X-Api-Key: {{API_KEY}}
Content-Type: application/json

{
    "video_ids": []
}